### ISSUE TITLE
confirm format of INBO test data

### ISSUE THREAD

**Issue by fredericpiesschaert** [DOV-Vlaanderen/groundwater-logger-validation#1]
@DavorJ a first batch of test files is available at https://github.com/DOV-Vlaanderen/groundwater-logger-validation/tree/master/data/raw/inbo
please check if the format is convenient. More details in https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/master/data/README.md

**Comment by DavorJ** [comment]
Format is OK for me. We will have to discuss it though, since csv-files depend on encoding, delimitation, timestamp-format, etc.

**Comment by DavorJ** [comment]
Encoding: UTF-8
Delimiter: ,
Decimal: ,
Quotes: "
Timestamp: 5/06/2009 12:00:00 +01:00

```
df <- data.table::fread(logger_path, dec = ",")
df[, DRME_OCR_UTC_DTE := as.POSIXct(gsub("(.*):", "\\1", DRME_OCR_UTC_DTE),
                                    format = "%d/%m/%Y %H:%M:%S %z", tz = 'UTC')]
```
