### ISSUE TITLE
outliers comparison

### ISSUE THREAD

**Issue by DavorJ** [DOV-Vlaanderen/groundwater-logger-validation#10]
To be able to compare different algorithm/approaches for outliers, I made a comparison pdf, available [here](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/outliers/src/r/outliers/outliers_comparison.pdf).

These can currently be compared:
* DRME_DMST_CDE 
* v0.01 (no a-priori info)
* v0.02 (with a-priori info)

**Comment by fredericpiesschaert** [comment]
with a-priori info is the way to go, DRME_DMST_CDE is not useful for validation of the outlier algorithm
