### ISSUE TITLE
outliers_v0.01 validation

### ISSUE THREAD

**Issue by DavorJ** [DOV-Vlaanderen/groundwater-logger-validation#2]
Version 0.01 is purely based on input-sensor-data (DRME_DRU), without any a-priori assumptions, based on [Leys (2013)](https://dipot.ulb.ac.be/dspace/bitstream/2013/139499/1/Leys_MAD_final-libre.pdf). In short, a very robust outlier detection approach based on noise-normality assumption (with possibility of extension to other distributions).

[Here](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/outliers/src/r/outliers/outliers_v0.01.pdf) are the results. Red dots are outliers. Pdf can be downloaded.

I think that for pressure and temperature, we could get better results if we take a-priori information into account. I will implement this in v0.02.

cc @fredericpiesschaert

**Comment by fredericpiesschaert** [comment]
We all agree that a priori assumptions are needed, so I think we can close this issue
