### ISSUE TITLE
Outliers: documentation validation

### ISSUE THREAD

**Issue by DavorJ** [DOV-Vlaanderen/groundwater-logger-validation#26]
[Here](http://htmlpreview.github.io/?https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/master/gwloggeR/vignettes/gwloggeR.html) is the first step towards documentation of the package.

I still have to choose a good way -- there exist several -- for an overall view of documentation: function explanation + vignettes.

_To be continued..._

**Comment by DavorJ** [comment]
Simulation section added.

**Comment by fredericpiesschaert** [comment]
documentation now available on https://dov-vlaanderen.github.io/groundwater-logger-validation/gwloggeR/docs/index.html
