### ISSUE TITLE
a-priori air pressure data

### ISSUE THREAD

**Issue by DavorJ** [DOV-Vlaanderen/groundwater-logger-validation#29]
I moved the apriori data to `gwloggeR\data-raw\apriori-air-pressure` since (1) it is related to the package and (2) because we already have the same data files in `data\raw\inbo`.

The load and analysis code is in [apriori-air-pressure.R](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/master/gwloggeR/data-raw/apriori-air-pressure.R) file. (Cf. [here](http://r-pkgs.had.co.nz/data.html#data-data) for raw data integration in packages.)

**An overview:**
Raw data:
![image](https://user-images.githubusercontent.com/4161918/61657647-ba8e5100-acc3-11e9-9ed9-5ea1ec32f31c.png)
Aggregated data (day):
![image](https://user-images.githubusercontent.com/4161918/61658647-1528ac80-acc6-11e9-97c8-1fd8f448eee9.png)
![image](https://user-images.githubusercontent.com/4161918/61661164-c3832080-accb-11e9-8d28-5036f122a311.png)
The green curve s the robust estimate for in v0.02 (mean = 1033.317 // sd = 9.586297). The yellow one is the old estimate (1034.2 // 9.93342). 

![image](https://user-images.githubusercontent.com/4161918/61658669-2376c880-acc6-11e9-8a2a-ee862eb6ba3b.png)

Couple of notes:
* Some data is is high frequency (like BAOL033X) which has 20x or more datapoints than others, and thus has a higher weight on the distribution. Thus I aggregated the data by day.
* Are BAOL040X and BAOL010X and BAOL094X from the same region? And BAOL070X? This latter might be amplifying the left skewness. 
* Only data with a timestamp is taken into consideration.
* Modeling the skewness with a kernel remains an option. 

TODO: make a comparison for v0.02 old vs. new, although I think the results will be very similar.

**Comment by DavorJ** [comment]
v0.02 based on new estimates (mean = 1033.317 // sd = 9.586297) I dubbed v0.03. The comparison can be found [here](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/master/src/r/outliers/outliers_comparison_inbo.pdf) between v0.01, v0.02 and v0.03.

The results of v0.03 are very similar to v0.02 for air pressure. For example, here the first outlier is detected in v0.03, but not in v0.02:
![image](https://user-images.githubusercontent.com/4161918/61743514-c2b6c100-ad95-11e9-8bb5-e632171db92d.png)

**Comment by DavorJ** [comment]
It was noted in the previous meeting that height differences might be causing the skewness. So asking the user to supply sensor elevation might be a way of further improvement.

**Comment by fredericpiesschaert** [comment]
I agree, but at this moment implementing sensor elevation seems low priority to me.

**Comment by fredericpiesschaert** [comment]
added a new issue for height, see https://github.com/DOV-Vlaanderen/groundwater-logger-validation/issues/39
