### ISSUE TITLE
outliers_v0.02 validation

### ISSUE THREAD

**Issue by DavorJ** [DOV-Vlaanderen/groundwater-logger-validation#3]
This method was only used on BAOL data. First, median and MAD were estimated based on all available data:
![image](https://user-images.githubusercontent.com/4161918/58121822-8e454e00-7c08-11e9-8bda-06b0b3442f44.png)

Subsequently, this information was used to detect outliers, similar to [v0.01](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/issues/2#issue-446154645).

The results are [here](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/outliers/src/r/outliers/outliers_v0.02.pdf). 

This method, using a-priori information, is good for flagging cases such as BAOL018X_42112 that contain unrealistic pressure measurements.

_To be discussed:_ whether a-priori information could be used for other data (besides BAOL).

cc @fredericpiesschaert

**Comment by fredericpiesschaert** [comment]
excellent optimisation for air pressure data. All time max and min pressure measured in Ukkel are 1048 hPa  and 956,6 hPa, equalling 1069 and 975 cmH20. Seems like a perfect match with the frequency distribution.

**Comment by DavorJ** [comment]
_To be discussed:_ units.

Now that you mention units: I am wondering whether all these sensors are using the same units:
![image](https://user-images.githubusercontent.com/4161918/58285249-b2419480-7dac-11e9-9a64-d1b8e361153a.png)

BAOL089, BAOL079 and BAOL006 seem to be on a different scale?

**Comment by fredericpiesschaert** [comment]
@DavorJ some loggers use mBar, some cmH2O, but all values are recalculated to cmH2O during import in the db. Hence all input-data have the same unit for INBO-data, but this definitely should be discussed with the other partners

**Comment by fredericpiesschaert** [comment]
I checked this with Mathias and BAOL089, BAOL079 and BAOL006 are indeed in mBar. In the new Watina, all values are converted to cmH20 during import, but these were values of old imports when the conversion was not yet implemented. I will fix this in the db and generate new BAOL-files to test with.

**Comment by DavorJ** [comment]
Added support for "diver" data. Lower bound is determined by "air pressure" a-priori information, and upper bound is determined based on v0.01.

**Comment by DavorJ** [comment]
Continued in #29 (v0.03) which is based on selected apriori air pressure data. Closing.
