### ISSUE TITLE
Hydrostatic pressure differences in function of time

### ISSUE THREAD

**Issue by DavorJ** [DOV-Vlaanderen/groundwater-logger-validation#32]
Idea is to analyze the behavior of differences in hydrostatic pressure, and use that as apriori information for further work on outliers (AO), levelshifts (LS) and temporal changes (TC).

First, a selection of hydrostatic pressure data was made that does not contain any AO, LS and TC and thus can be used for a-priori information. This selected data can be found [here](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/blob/master/gwloggeR/data-raw/apriori-hydrostatic-pressure.pdf).

Based on this data, the following plots have been made:

![image](https://raw.githubusercontent.com/DOV-Vlaanderen/groundwater-logger-validation/master/src/r/apriori/apriori_hydrostatic_pressure_cumulative_density.png)

This plot shows the density of differences in function of time. The following plot is similar but instead of density gradient is shows the median (black) and 0.975 quantile (red) of the absolute differences.

![image](https://github.com/DOV-Vlaanderen/groundwater-logger-validation/raw/master/src/r/apriori/apriori_hydrostatic_pressure_quantiles.png)

So how can we use this information? Well, we extract from it that (for example) it is very unlikely that an absolute difference of more than 25 cmH2O occurs after a 12 hours time-interval. If it does, then this might be an AO, LS or TC. We can further do the same for any interval.

It also shows that time-intervals of 6 hours are very uncertain due to tidal movements. Tidal movements on the other hand are location-specific, and can be (robustly) estimated on individual basis, to decrease this uncertainty.

**Comment by fredericpiesschaert** [comment]
@DavorJ this can be closed as well I guess? Should I make a new ticket for the tidal cycle-enhancement?

**Comment by DavorJ** [comment]
(y). Also, these other posts that are meant as information can be closed too from my part.
