### ISSUE TITLE
GitHub Pages for gwloggeR documentation

### ISSUE THREAD

**Issue by DavorJ** [DOV-Vlaanderen/groundwater-logger-validation#37]
@fredericpiesschaert, I wanted to make a Project Page for  `gwloggeR` following this [manual](https://help.github.com/en/articles/creating-project-pages-using-the-command-line).

1) Setup `gh-pages` branch with html files (done)
2) This link should work: https://dov-vlaanderen.github.io/groundwater-logger-validation
3) If (2) works, then this one should also work: https://dov-vlaanderen.github.io/groundwater-logger-validation/gwlogger/docs

But for (2) and (3) I am getting:

![image](https://user-images.githubusercontent.com/4161918/65184928-cea5c300-da66-11e9-9135-5387a80eaabe.png)

Any idea why this is failing? Typo somewhere? From what I read from the manual, one reason for failure would be if DOV-Vlaanderen is using a [custom domain](https://help.github.com/en/articles/using-a-custom-domain-with-github-pages). Is it? If so, which one?

**Comment by fredericpiesschaert** [comment]
I really have no idea, @stijnvanhoey @Roel does this ring a bell with you?

**Comment by Roel** [comment]
We certainly do not have a custom domain.

I reselected 'gh-pages' branch in the project settings and picked a theme, and that seems to have done the trick. Link 2 works now: https://dov-vlaanderen.github.io/groundwater-logger-validation

Mind that everything in the URL except the domain name itself is case sensitive, so link 3 should be https://dov-vlaanderen.github.io/groundwater-logger-validation/gwloggeR/docs/ (and this works now too).

**Comment by DavorJ** [comment]
@Roel, bedankt!
