### ISSUE TITLE
package interface: detect_outliers(...)

### ISSUE THREAD

**Issue by DavorJ** [DOV-Vlaanderen/groundwater-logger-validation#6]
I had the following interface/specification in mind for `detect_xxxxx()` functions:

```
# In case of a vector
x <- c(1:10, 100)
detect_outliers(x)

# In case of a dataframe, select the column:
detect_outliers(cars$dist)

# Or use the tidyverse approach:
library(magrittr)
cars %>% plyr::mutate("outlier" = detect_outliers(dist))
```

Any remarks, suggestions or other ideas?

cc @stijnvanhoey

**Comment by stijnvanhoey** [comment]
I'm fine with a vector-oriented workflow which can be integrated within the tidyverse approach using `mutate` statement. 

Small remark: use `dplyr::mutate()` rather than `plyr::mutate()`.

**Comment by fredericpiesschaert** [comment]
@DavorJ This might be a complete nonsens comment, but I'll take the risk: I read that vectors are often converted to [time series objects](https://www.tutorialspoint.com/r/r_time_series_analysis.htm), would that improve performance of e.g. arima in tsoutliers?

**Comment by DavorJ** [comment]
@fredericpiesschaert vectors must be converted to time series objects for ARIMA models. Conversion is thus either implicit or explicit.

If you look in `stats::arima()` function, you see the line `x <- as.ts(x)` early on. That is implicit conversion in case someone "forgets" to do so explicitly.

Thus `arima(1:10)` and `arima(ts(1:10))` are equivalent, and the speed is the same. Internally, for parameter estimation etc., only the numerical/vector part is used anyway.
